sudo: false

language: ruby

rvm:
- 2.3.1

cache: bundler

install:
- bundle install

branches:
  only:
    - master

script: build.sh

# before_script:
#   - git config --global user.email "5j4@users.noreply.github.com"
#   - git config --global user.name "5j4"
#   - git remote rm origin
#   - git remote add origin https://user:${DEPLOY_TOKEN}@${GITHUB_REPO}

# script: bundle exec jekyll build

# after_success:
#   - bash scripts/deploy.sh

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    - GITHUB_REPO: github.com/5j4/mariusdroughtproject.org.git
    - SOURCE_BRANCH: master
    - TARGET_BRANCH: gh-pages
    # secure: encrypted-github-personal-access-token (DEPLOY_TOKEN)
    - secure: "HaelMbXcXP41sd3nhd6KiNLh2R5tODIOaXseX4TiFuWYYxpUzyYn7ipQZMExyCX0lxzW7ckSQEWdfopcSuZb2T4iIDfMBpC8biRkBsFcqezD0Foce1E+1bANk7OEjtPsrQklxr731LfjOgRy2fT2SVfTEmU8ij+u7s412dfTF67ySOSRQQ/R58gcmRMrHUtjidjHfVi9zVP528JzolUZjDpfgSn/Aqf+4led/wz4i4Q9JsB78k4LjDWmAxALkp0b5Uf+XphJgfQ6zU3LQVWCjJfbFmKFuIudw3SNw9RCIKy9gE/i5MaMiVgoOow/Etvw9MRooYqcMiO7KwkFMYQGrDOr7+Z7vXa5okotZWsJeXWRKEzxzyqRmzc7whNXF7AieR3k2ktf9Fi+aHnlNVn8pVK0u3P26qIyYXNh6s4px2Z8WwxHa3Rv/QKOL6YOqfamyjrEY/74WlWWPJDGFgIdAqXMnRIMlMxXrcIN6jS63dAqABQSZPl1beHP+9YJMcY/VUCJXoBuZbQIRwApXIf+lRzo7gHgCHGoOjF1Nnn5zFwu+lEGLQKLqudCqOS1EwicQIXA+a82MQMZMw5RaZLX0vZSLbfdVg0JGEPeS0Yxt6MawdsLafI/JBpT5ZTd6OGHFM+L37o0AvL5aGkRexlETkz9anaku4gotPbnfFGn30Y="