# GitHub
username: 5j4
repo: 5j4.github.io
branch: master

# Jekyll source / destination
source: .
destination: _site

exclude: ["vendor"]
include: ["_pages"]

# gems:
#   # - jekyll
#   - sass
#   - font-awesome-sass
#   - jekyll-assets
#   - jekyll-gist
#   - uglifier
#   - mini_magick

# gems: [jekyll-gist, jekyll-assets, sass, uglifier]

permalink: /:title/

# Pages permalink
defaults:
  -
    scope:
      type: "pages"
    values:
      permalink: /:path/:basename:output_ext

markdown: kramdown
# kramdown config to force interpretation into html block
# kramdown:
#   parse_block_html: true

baseurl: /mariusdroughtproject.org

# ------------------------------------------------------------------------------
sass:
  sass_dir: _sass
  style: compressed

# ------------------------------------------------------------------------------
# jekyll-assets
# assets:
#     dirname: assets
#     baseurl: /mariusdroughtproject.org/assets/
#     sources:
#       - _assets/css
#       - _assets/images
#       - _assets/js
#     # compress:
#     #     css: sass
#     #     js: uglifier
#     # features:
#     #     liquid: true
#     #     automatic_img_alt: true
#     #     automatic_img_size: false
#     digest: true

# ------------------------------------------------------------------------------
assets_url: /mariusdroughtproject.org/assets
images_url: /mariusdroughtproject.org/assets/images
data_url: /mariusdroughtproject.org/assets/data

science_url: /mariusdroughtproject.org/dashboard/science
dpe_url: /mariusdroughtproject.org/dashboard/dpe

# ------------------------------------------------------------------------------
# prose.io config
# https://github.com/prose/prose/wiki/Getting-Started
# ------------------------------------------------------------------------------
prose:
  #rooturl: ''
  #siteurl: "https://5j4.github.io/mariusdroughtproject.org/"
  relativeLinks: "http://5j4.github.io/mariusdroughtproject.org/links.jsonp"
  media: 'assets/images'
  ignore:
    - .gitignore
    - Gemfile
    - Gemfile.lock
    - README.md
    - _config.yml
    - links.jsonp
    - favicon.ico
    - robots.txt
    - /_site
    - /_layouts
    - /_plugins
    - /assets
    - .travis.yml
    - .jekyl-metadata
    - build.sh
    - _sass
    - .nojekyll
    - bundle
  metadata:
    _pages:
      - name: "layout"
        field:
          element: "hidden"
          value: "default"
      - name: "published"
        field:
          element: "checkbox"
          label: "Published"
          help: "true = live/visible, false = draft/hidden"
          value: true
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          help: "1) Replace 'PAGE_NAME' with the name of the page, 2) the link should start AND end with a forward slash (/)"
          value: "/PAGE_NAME/"
      - name: "subsection"
        field:
          element: "text"
          label: "Subsection"
          value: ""
      - name: "_title"
        field:
          element: "text"
          label: "Title"
          help: "page title"
          value: ""
      - name: "sub_title"
        field:
          element: "text"
          label: "Subtitle"
          value: ""
    _pages/dashboard/science:
      - name: "layout"
        field:
          element: "hidden"
          label: "Related links"
          value: "science"
      - name: "published"
        field:
          element: "checkbox"
          label: "Published"
          help: "true = live/visible, false = draft/hidden"
          value: true
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          help: "1) Replace 'PAGE_NAME' with the name of the page, 2) the link should start AND end with a forward slash (/)"
          value: "/dashboard/science/PAGE_NAME/"
      - name: "subsection"
        field:
          element: "text"
          label: "Subsection"
          value: ""
      - name: "_title"
        field:
          element: "text"
          label: "Title"
          help: "page title"
          value: ""
      - name: "sub_title"
        field:
          element: "text"
          label: "Subtitle"
          value: ""
    _pages/dashboard/dpe:
      - name: "layout"
        field:
          element: "hidden"
          value: "management"
      - name: "published"
        field:
          element: "checkbox"
          label: "Published"
          help: "true = live/visible, false = draft/hidden"
          value: true
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          help: "1) Replace 'PAGE_NAME' with the name of the page, 2) the link should start AND end with a forward slash (/)"
          value: "/dashboard/dpe/PAGE_NAME/"
      - name: "subsection"
        field:
          element: "text"
          label: "Subsection"
          value: ""
      - name: "_title"
        field:
          element: "text"
          label: "Title"
          help: "page title"
          value: ""
      - name: "sub_title"
        field:
          element: "text"
          label: "Subtitle"
          value: ""
